
package org.us.booking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UnitedSolutions", targetNamespace = "http://booking.us.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnitedSolutions {


    /**
     * 
     * @param strFlightId
     * @param strReturnFlightId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Reservation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reservation", targetNamespace = "http://booking.us.org/", className = "org.us.booking.Reservation")
    @ResponseWrapper(localName = "ReservationResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.ReservationResponse")
    public String reservation(
            @WebParam(name = "strFlightId", targetNamespace = "")
            String strFlightId,
            @WebParam(name = "strReturnFlightId", targetNamespace = "")
            String strReturnFlightId);

    /**
     * 
     * @param strContactEmail
     * @param strFlightId
     * @param strContactName
     * @param strContactMobile
     * @param strReturnFlightId
     * @param strPassengerDetail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IssueTicket")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IssueTicket", targetNamespace = "http://booking.us.org/", className = "org.us.booking.IssueTicket")
    @ResponseWrapper(localName = "IssueTicketResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.IssueTicketResponse")
    public String issueTicket(
            @WebParam(name = "strFlightId", targetNamespace = "")
            String strFlightId,
            @WebParam(name = "strReturnFlightId", targetNamespace = "")
            String strReturnFlightId,
            @WebParam(name = "strContactName", targetNamespace = "")
            String strContactName,
            @WebParam(name = "strContactEmail", targetNamespace = "")
            String strContactEmail,
            @WebParam(name = "strContactMobile", targetNamespace = "")
            String strContactMobile,
            @WebParam(name = "strPassengerDetail", targetNamespace = "")
            String strPassengerDetail);

    /**
     * 
     * @param strAgencyId
     * @param strPnoNo
     * @param strTicketNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItinerary")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetItinerary", targetNamespace = "http://booking.us.org/", className = "org.us.booking.GetItinerary")
    @ResponseWrapper(localName = "GetItineraryResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.GetItineraryResponse")
    public String getItinerary(
            @WebParam(name = "strPnoNo", targetNamespace = "")
            String strPnoNo,
            @WebParam(name = "strTicketNo", targetNamespace = "")
            String strTicketNo,
            @WebParam(name = "strAgencyId", targetNamespace = "")
            String strAgencyId);

    /**
     * 
     * @param strAgencyId
     * @param strAirlineId
     * @param strPnrNo
     * @param strUserId
     * @param strPassword
     * @param strTicketNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelReservation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelReservation", targetNamespace = "http://booking.us.org/", className = "org.us.booking.CancelReservation")
    @ResponseWrapper(localName = "CancelReservationResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.CancelReservationResponse")
    public String cancelReservation(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId,
            @WebParam(name = "strPassword", targetNamespace = "")
            String strPassword,
            @WebParam(name = "strAgencyId", targetNamespace = "")
            String strAgencyId,
            @WebParam(name = "strPnrNo", targetNamespace = "")
            String strPnrNo,
            @WebParam(name = "strTicketNo", targetNamespace = "")
            String strTicketNo,
            @WebParam(name = "strAirlineId", targetNamespace = "")
            String strAirlineId);

    /**
     * 
     * @param strFlightId
     * @param strUserId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFlightDetail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetFlightDetail", targetNamespace = "http://booking.us.org/", className = "org.us.booking.GetFlightDetail")
    @ResponseWrapper(localName = "GetFlightDetailResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.GetFlightDetailResponse")
    public String getFlightDetail(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId,
            @WebParam(name = "strFlightId", targetNamespace = "")
            String strFlightId);

    /**
     * 
     * @param strAgencyId
     * @param strFromDate
     * @param strToDate
     * @param strUserId
     * @param strPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SalesReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SalesReport", targetNamespace = "http://booking.us.org/", className = "org.us.booking.SalesReport")
    @ResponseWrapper(localName = "SalesReportResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.SalesReportResponse")
    public String salesReport(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId,
            @WebParam(name = "strPassword", targetNamespace = "")
            String strPassword,
            @WebParam(name = "strAgencyId", targetNamespace = "")
            String strAgencyId,
            @WebParam(name = "strFromDate", targetNamespace = "")
            String strFromDate,
            @WebParam(name = "strToDate", targetNamespace = "")
            String strToDate);

    /**
     * 
     * @param strContactEmail
     * @param strFlightId
     * @param strContactName
     * @param strContactMobile
     * @param strReturnFlightId
     * @param strPassengerDetail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IssueTicketB2B")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IssueTicketB2B", targetNamespace = "http://booking.us.org/", className = "org.us.booking.IssueTicketB2B")
    @ResponseWrapper(localName = "IssueTicketB2BResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.IssueTicketB2BResponse")
    public String issueTicketB2B(
            @WebParam(name = "strFlightId", targetNamespace = "")
            String strFlightId,
            @WebParam(name = "strReturnFlightId", targetNamespace = "")
            String strReturnFlightId,
            @WebParam(name = "strContactName", targetNamespace = "")
            String strContactName,
            @WebParam(name = "strContactEmail", targetNamespace = "")
            String strContactEmail,
            @WebParam(name = "strContactMobile", targetNamespace = "")
            String strContactMobile,
            @WebParam(name = "strPassengerDetail", targetNamespace = "")
            String strPassengerDetail);

    /**
     * 
     * @param strAirlineId
     * @param strTicketNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Refund")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Refund", targetNamespace = "http://booking.us.org/", className = "org.us.booking.Refund")
    @ResponseWrapper(localName = "RefundResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.RefundResponse")
    public String refund(
            @WebParam(name = "strTicketNo", targetNamespace = "")
            String strTicketNo,
            @WebParam(name = "strAirlineId", targetNamespace = "")
            String strAirlineId);

    /**
     * 
     * @param strCurrentDate
     * @param strAirlineId
     * @param strPnrNo
     * @param strNewDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Reschedule")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reschedule", targetNamespace = "http://booking.us.org/", className = "org.us.booking.Reschedule")
    @ResponseWrapper(localName = "RescheduleResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.RescheduleResponse")
    public String reschedule(
            @WebParam(name = "strPnrNo", targetNamespace = "")
            String strPnrNo,
            @WebParam(name = "strAirlineId", targetNamespace = "")
            String strAirlineId,
            @WebParam(name = "strCurrentDate", targetNamespace = "")
            String strCurrentDate,
            @WebParam(name = "strNewDate", targetNamespace = "")
            String strNewDate);

    /**
     * 
     * @param strRescheduleId
     * @param strOperation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RescheduleSave")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RescheduleSave", targetNamespace = "http://booking.us.org/", className = "org.us.booking.RescheduleSave")
    @ResponseWrapper(localName = "RescheduleSaveResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.RescheduleSaveResponse")
    public String rescheduleSave(
            @WebParam(name = "strRescheduleId", targetNamespace = "")
            String strRescheduleId,
            @WebParam(name = "strOperation", targetNamespace = "")
            String strOperation);

    /**
     * 
     * @param strAgencyId
     * @param strLastName
     * @param strPnrNo
     * @param strUserId
     * @param strPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPnrDetail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetPnrDetail", targetNamespace = "http://booking.us.org/", className = "org.us.booking.GetPnrDetail")
    @ResponseWrapper(localName = "GetPnrDetailResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.GetPnrDetailResponse")
    public String getPnrDetail(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId,
            @WebParam(name = "strPassword", targetNamespace = "")
            String strPassword,
            @WebParam(name = "strAgencyId", targetNamespace = "")
            String strAgencyId,
            @WebParam(name = "strPnrNo", targetNamespace = "")
            String strPnrNo,
            @WebParam(name = "strLastName", targetNamespace = "")
            String strLastName);

    /**
     * 
     * @param strAirlineId
     * @param strUserId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckBalance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CheckBalance", targetNamespace = "http://booking.us.org/", className = "org.us.booking.CheckBalance")
    @ResponseWrapper(localName = "CheckBalanceResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.CheckBalanceResponse")
    public String checkBalance(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId,
            @WebParam(name = "strAirlineId", targetNamespace = "")
            String strAirlineId);

    /**
     * 
     * @param strAgencyId
     * @param strFlightDate
     * @param intChild
     * @param strTripType
     * @param strNationality
     * @param intAdult
     * @param strSectorTo
     * @param strSectorFrom
     * @param strUserId
     * @param strPassword
     * @param strReturnDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FlightAvailability")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FlightAvailability", targetNamespace = "http://booking.us.org/", className = "org.us.booking.FlightAvailability")
    @ResponseWrapper(localName = "FlightAvailabilityResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.FlightAvailabilityResponse")
    public String flightAvailability(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId,
            @WebParam(name = "strPassword", targetNamespace = "")
            String strPassword,
            @WebParam(name = "strAgencyId", targetNamespace = "")
            String strAgencyId,
            @WebParam(name = "strSectorFrom", targetNamespace = "")
            String strSectorFrom,
            @WebParam(name = "strSectorTo", targetNamespace = "")
            String strSectorTo,
            @WebParam(name = "strFlightDate", targetNamespace = "")
            String strFlightDate,
            @WebParam(name = "strReturnDate", targetNamespace = "")
            String strReturnDate,
            @WebParam(name = "strTripType", targetNamespace = "")
            String strTripType,
            @WebParam(name = "strNationality", targetNamespace = "")
            String strNationality,
            @WebParam(name = "intAdult", targetNamespace = "")
            String intAdult,
            @WebParam(name = "intChild", targetNamespace = "")
            String intChild);

    /**
     * 
     * @param strUserId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SectorCode")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SectorCode", targetNamespace = "http://booking.us.org/", className = "org.us.booking.SectorCode")
    @ResponseWrapper(localName = "SectorCodeResponse", targetNamespace = "http://booking.us.org/", className = "org.us.booking.SectorCodeResponse")
    public String sectorCode(
            @WebParam(name = "strUserId", targetNamespace = "")
            String strUserId);

}
