
package org.us.booking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnitedSolutionsService", targetNamespace = "http://booking.us.org/", wsdlLocation = "http://dev.usbooking.org/us/UnitedSolutions?wsdl")
public class UnitedSolutionsService
    extends Service
{

    private final static URL UNITEDSOLUTIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNITEDSOLUTIONSSERVICE_EXCEPTION;
    private final static QName UNITEDSOLUTIONSSERVICE_QNAME = new QName("http://booking.us.org/", "UnitedSolutionsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev.usbooking.org/us/UnitedSolutions?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNITEDSOLUTIONSSERVICE_WSDL_LOCATION = url;
        UNITEDSOLUTIONSSERVICE_EXCEPTION = e;
    }

    public UnitedSolutionsService() {
        super(__getWsdlLocation(), UNITEDSOLUTIONSSERVICE_QNAME);
    }

    public UnitedSolutionsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNITEDSOLUTIONSSERVICE_QNAME, features);
    }

    public UnitedSolutionsService(URL wsdlLocation) {
        super(wsdlLocation, UNITEDSOLUTIONSSERVICE_QNAME);
    }

    public UnitedSolutionsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNITEDSOLUTIONSSERVICE_QNAME, features);
    }

    public UnitedSolutionsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnitedSolutionsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnitedSolutions
     */
    @WebEndpoint(name = "UnitedSolutionsPort")
    public UnitedSolutions getUnitedSolutionsPort() {
        return super.getPort(new QName("http://booking.us.org/", "UnitedSolutionsPort"), UnitedSolutions.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnitedSolutions
     */
    @WebEndpoint(name = "UnitedSolutionsPort")
    public UnitedSolutions getUnitedSolutionsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://booking.us.org/", "UnitedSolutionsPort"), UnitedSolutions.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNITEDSOLUTIONSSERVICE_EXCEPTION!= null) {
            throw UNITEDSOLUTIONSSERVICE_EXCEPTION;
        }
        return UNITEDSOLUTIONSSERVICE_WSDL_LOCATION;
    }

}
